const judges = [
  'A. Jack Snite',
  'Abbe F. Fletman',
  'Abram Frank Reynolds',
  'Adam Beloff',
  'Albert W. Sheppard',
  'Alex Bonavitacola',
  'Alfred J. DiBona',
  'Alice Dubow',
  'Allan L. Tereshko',
  'Amanda Cooperman',
  'Angeles Roca',
  'Angelo J. Foglietta',
  'Ann Butchart',
  'Anne Marie B. Coyle',
  'Anthony George Kyriakakis',
  'Anthony J. DeFino',
  'Anu Koodathil',
  'Arnold L. New',
  'Arthur S. Kafrissen',
  'Ayinde Warren',
  'Barbara A. McDermott',
  'Barry F. Feudale',
  'Benjamin Lerner',
  'Bernice DeAngelis',
  'Bradley K. Moss',
  'Brandon A. Harris',
  'Brenda Frazier-Clemons',
  'Carmella Jacquinto',
  'Carolyn Engel Temin',
  'Carolyn H. Nichols',
  'Charles A. Ehrlich',
  'Charles B. Smith',
  'Charles Hayden',
  'Charles J. Cunningham',
  'Chris R. Wogan',
  'Christine M. Hope',
  'Christopher Mallios',
  'Craig M. Washington',
  'Crystal Powell',
  'Daniel D. McCaffery',
  'Daniel J. Anders',
  'David C. Shuter',
  'David H. Conroy',
  'Dawn A. Segal',
  'Deborah D. Cianfrani',
  'Denis P. Cohen',
  'Diana L. Anhalt',
  'Donna Woelpper',
  'Doris A. Pechkurow',
  'Earl W. Trent',
  'Earlene Green',
  'Edgar Campbell',
  'Edward C. Wright',
  'Edward E. Russell',
  'Elizabeth Jackson',
  'Ellen Ceisler',
  'Felice Rowley Stack',
  'Flora Barth Wolf',
  'Francis J. Rebstock',
  'Frank Krewdo',
  'Frank Palumbo',
  'Frank T. Brady',
  'Frederica Massiah-Jackson',
  'Genece E. Brinkley',
  'Georganne V. Daher',
  'Gerard A. Kosinski',
  'Giovanni O. Campbell',
  'Glenn B. Bronson',
  'Glynnis Hill',
  'Grainne Lynn',
  'Gregory E. Smith',
  'Gwendolyn N. Bright',
  'Harold M. Kane',
  'Harvey W. Robbins',
  'Henry Lewandowski',
  'Holly J. Ford',
  'Howland Abramson',
  'Idee C. Fox',
  "J. Scott O'Keefe",
  'Jacquelyn Frazier-Lyde',
  'James M. DeLeon',
  'James Murray Lynn',
  "James O'Brien",
  'Jane Cutler Greenspan',
  'Jane M. Rice',
  'Jeffrey P. Minehart',
  'Jennifer Schultz',
  'Jimmie Moore',
  'Joan A. Brown',
  'Joel S. Johnson',
  'Joffie C. Pittman',
  'John DiGiorgio',
  "John J. O'Grady",
  'John Padova',
  'Jonathan Q. Irvine',
  'Joseph C. Bruno',
  'Joseph C. Waters',
  "Joseph D. O'Keefe",
  "Joseph J. O'Neill",
  'Joyce O. Eubanks',
  'Kai Scott',
  'Karen Shreeves-Johns',
  'Karen Y. Simmons',
  'Kathryn Streeter Lewis',
  'Kenneth J. Powell',
  'Kevin M. Dougherty',
  'Leon Tucker',
  'Lillian Ransom',
  'Linda Carpenter',
  'Lisa M. Rau',
  'Lisette Shirdan-Harris',
  'Lori A. Dumas',
  'Lucretia C. Clemons',
  'Lydia Y. Kirkland',
  'M. Teresa Sarmina',
  'Maria McLaughlin',
  'Marisa Shuter',
  'Marissa Brumbach',
  'Marlena Siegel',
  'Marlene F. Lachman',
  'Marsha H. Neifield',
  'Martin S. Coleman',
  'Marvin Louis Williams',
  'Mary D. Colins',
  'Matthew S. Wolf',
  'Mia Roberts Perez',
  'Michael Erdos',
  'Michael Fanning',
  'Michael Sanuck',
  'NA Attorney General of Pennsylvania',
  'NA NA',
  'NA Superior Court of Pennsylvania',
  'NA Supreme Court of Pennsylvania',
  'Nazario Jimenez',
  'Nina N. Wright Padilla',
  'Pamela Pryor Dembe',
  'Patrick F. Dugan',
  'Paul Peter Panepinto',
  'Paula A. Patrick',
  'Peter F. Rogers',
  'R Seth Williams',
  'R. Barry McAndrews',
  'Ramy I. Djerassi',
  'Rayford A. Means',
  'Rebecca Sue Barnes',
  'Renee Cardwell Hughes',
  'Ricardo C. Jackson',
  'Richard J. Gordon',
  'Robert J. Rebstock',
  'Robert M. Shaffer',
  'Robert P. Coleman',
  'Robert S. Blasi',
  'Roger F. Gordon',
  'Ronald C. Nagle',
  'Rosalyn K. Robinson',
  'Rose DeFino-Nastasi',
  'Roxanne Covington',
  'Rulla Moor',
  'S. Gerald Corso',
  'Sandy L.V. Byrd',
  'Scott DiClaudio',
  'Seamus P. McCaffery',
  'Sean F. Kennedy',
  'Shanese I. Johnson',
  'Sharon Williams-Losier',
  'Sheila M. Bedford',
  'Sheila Woods-Skipper',
  'Sheldon C. Jelin',
  'Shelley Robins New',
  'Sierra Thomas Street',
  'Stella Tsai',
  'Stephanie Sawyer',
  'Steven R. Geroff',
  'Susan Carmody',
  'Susan I. Schulman',
  'T. Francis Shields',
  'Teresa Carr Deni',
  'Thomas Dempsey',
  'Thomas F. Gehret',
  'Thomas G. Gavin',
  'Timika Lane',
  'Tracy Brandeis-Roman',
  'Vincent L. Johnson',
  'Vincent N. Melchiorre',
  'Walter Olszewski',
  'Warren Hogeland',
  'Wendy L. Pew',
  'William Austin Meehan',
  'William J. Manfredi',
  'William J. Mazzola',
  'Willis W. Berry',
  'Zachary C. Shaffer',
];

export default judges;
