source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.1.2"

group :pull, :rails do
  gem "activesupport"
  gem "capybara"
  gem "nokogiri"
  gem "open-uri"
  gem "parallel"
  gem "pry"
  gem "selenium-webdriver"
end

group :rails do
  gem "bcrypt", "~> 3.1"
  gem "crono", "~> 1.1"
  gem "haml", "~> 5.2"
  gem "pg", "~> 1.1"
  gem "puma", "~> 5.0"
  gem "rails", "~> 7.0.1"
  gem "sinatra", "~> 2.2", require: nil

  # Windows does not include zoneinfo files, so bundle the tzinfo-data gem
  gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
  # Reduces boot times through caching; required in config/boot.rb
  gem "bootsnap", require: false
end

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end
